apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvMount | quote }}
      version: {{ .Values.vault.kvVersion | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMount | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount.name | quote }}
            namespace: {{ .Values.vault.serviceAccount.namespace | quote }}
            audiences:
              - {{ .Values.vault.audience | quote }}
